### ISSUE TITLE
More 3rd party panels

### ISSUE THREAD

**Issue by sontek** [Pylons/pyramid_debugtoolbar#110]
Right now we have a good base set of panels but I think it would be nice to also have panels that give better introspection on other services such as:

MongoDB
Redis
Memcached
ElasticSearch
HTML Validator

**Comment by JonnoFTW** [comment]
I made a mongodb panel here: https://gist.github.com/JonnoFTW/de331ac10f82a77150f260e2919a11b0

Should I go to the effort of packaging and publishing this?

**Comment by stevepiercy** [comment]
@JonnoFTW packaging it yourself or submitting a PR to this package? Pylons Project standards include 100% test coverage and documentation. See https://github.com/Pylons/pyramid_debugtoolbar/blob/master/contributing.md. I'm fairly sure a PR that meets the PP standards would be accepted.

**Comment by jvanasco** [comment]
@JonnoFTW two comments:

1. I think the package looks like a better version of pyramid_mongo which ships with it's own debugtoolbar, rather than a standalone debugtoolbar panel/app.  That's in part because you're setting it up the connection in a special way early on via `add_request_method`.

2. It would be nice if this printed out the mongo connection data and differentiated between what went to which server / connection.  I've worked on many apps where there are 2-4 mongo connections/databases.

**Comment by JonnoFTW** [comment]
@jvanasco to confirm, do you want me to make a separate repository/pip package or do you want me to make a pull request to this repo? 

I understand that my database connection approach is a bit different from the way other packages do it, namely I keep one `MongoClient` instance per app and add connection via `add_request_method`. This is considered best practice according to the pymongo docs: http://api.mongodb.com/python/current/faq.html#how-does-connection-pooling-work-in-pymongo where they recommend making one client per process. Reopening and closing a client every request has a significant performance hit.

I'm not sure if forcing people to use mongodb this way in their app is appropriate in order for them to use my toolbar. I looked and https://github.com/llacroix/pyramid_mongo does not include a debugtoolbar.

I've improved the toolbar a bit now to include cursor explanations, connection info, handling multiple connections and database/collection stats subtabs.

**Comment by jvanasco** [comment]
> On Jul 24, 2018, at 10:53 PM, Jonathan Mackenzie <notifications@github.com> wrote:
> 
> @jvanasco to confirm, do you want me to make a separate repository/pip package or do you want me to make a pull request to this repo?

IMHO,I think because of this line…

> I'm not sure if forcing people to use mongodb this way in their app is appropriate in order for them to use my toolbar. I looked and https://github.com/llacroix/pyramid_mongo does not include a debug toolbar.

...your toolbar would be a good standalone repo/pip package that competes with, and essentially replaces, pyramid_mongo.  i don’t know what to call it though.

you’re basically offering Pyramid Mongo with a built in toolbar.  i think that is amazing.

**Comment by JonnoFTW** [comment]
@jvanasco I've made two separate modules:

https://github.com/JonnoFTW/pyramid_mongodb

https://github.com/JonnoFTW/pyramid_mongodb_debugtoolbar

I hope these offer a superior experience over pyramid_mongo

**Comment by stevepiercy** [comment]
@JonnoFTW PyPI has problems rendering the readmes. See https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi for how to fix.

Also I'd like to help you promote the packages:
* Add to https://docs.pylonsproject.org/projects/pyramid-debugtoolbar/en/latest/#panel-and-ui-extras
* Add listings to [TryPyramid.com - Extending Pyramid](https://trypyramid.com/resources-extending-pyramid.html). See https://github.com/Pylons/trypyramid.com/issues/202 for details.
* Tweeting from @PylonsProject.
* You can post to https://groups.google.com/forum/#!forum/pylons-discuss

Please let me know.

**Comment by stevepiercy** [comment]
@JonnoFTW all done on my end.

Closing this issue to break it up into a separate issue for each of the ideas originally suggested. See #336, #337, #338, #339.
