### ISSUE TITLE
Feature Idea - Default Tab

### ISSUE THREAD

**Issue by jvanasco** [Pylons/pyramid_debugtoolbar#165]
What would others think about a customizable default tab ?

I find that i often want to jump into one of 3 tabs, and I spend a decent amount of time searching for them.  

The general ideas I had were:
- updating the toolbar to show a specific panel.  this could be javascript checking for a url fragment / hashbang, or a query param.  
- override the template for the "fixme" button.  this would let people 'hotlink' to one or more tabs.  this could be a config panel setting, or some hook/api.  ( i guess it could be monkeypatched too )

if anyone else would find this useful, let me know and i'll try coding it.

**Comment by mmerickel** [comment]
I think it'd be great to at least keep the same tab selected when clicking through requests. A url fragment could be used for this without much difficulty if someone wanted to contribute it to toolbar.js.

**Comment by mmerickel** [comment]
Closed via #272.
