### ISSUE TITLE
Error in FireFox

### ISSUE THREAD

**Issue by pppierre** [Pylons/pyramid_debugtoolbar#17]
Hello,

I am using git version of pyramid_debugtoolbar with the git version of pyramid. It seems to be a great and very useful tool.

I have just a remark:

In FireFox 5.0 (Debian Wheezy), it generates the two following errors:
Error in parsing value for 'left'. Declaration dropped.
Error in parsing value for 'top'. Declaration dropped.

And a suggestion:

The tab is a bit intrusive. We could set its size and position in configuration file.

Patrick.

**Comment by mmerickel** [comment]
The toolbar is hosted in a separate pyramid app now so these issues with your page failing to validate should no longer occur.
