### ISSUE TITLE
Profiling does not work for REST applications

### ISSUE THREAD

**Issue by wichert** [Pylons/pyramid_debugtoolbar#172]
I do the following:

1. Open the debug toolbar, go to the *Settings* tab and click the *Enable* checkmark so it turns green. 
1. Go to the *Global* tab, and then back to the *Settings* tab to confirm the checkmark is still green.
1. Go to the *History* tab.
1. Fire a single AJAX request, which uses the JSON renderer.
1. Click on the request in the left column, and go to the *Performance* panel. This says "*The profiler is not activated.*"
1. Go to the *Settings* tab again. The checkmark is now red.

**Comment by mmerickel** [comment]
It is possible to use the `debugtoolbar.active_panels` option in the INI now, as well as passing a cookie per-request. Both options are documented.

**Comment by mmerickel** [comment]
This doesn't actually solve the problem of trying to activate the toolbar from the UI and having it inactive for non-browser requests, but I think that's alright. I'd accept a PR that made this more clear in the toolbar settings UI. I'd prefer to update the UI versus add a central data store to the toolbar.

**Comment by wichert** [comment]
For this use case it would be very helpful if the toolbar could print a ``You can access the debug toolbar at http://127.0.0.1/_debug_toolbar/`` message on the console on app startup. That makes the toolbar discoverable in pure REST situations.

**Comment by mmerickel** [comment]
@wichert It'd have to be at first request or per-request because we don't know what url prefix the app is mounted (in my env I have 5 pyramid apps each with their own toolbar mounted from the same ini file).
