### ISSUE TITLE
debugtoolbar code/docs say it requires pyramid>=1.2dev but actually requires 1.4

### ISSUE THREAD

**Issue by lambacck** [Pylons/pyramid_debugtoolbar#183]
```invoke_subrequest``` was introduced in 1.4:
http://docs.pylonsproject.org/docs/pyramid/en/latest/narr/subrequest.html#invoking-a-subrequest

It gets used here:
https://github.com/Pylons/pyramid_debugtoolbar/blob/master/pyramid_debugtoolbar/toolbar.py#L200

Looks like it was introduced prior to 2.0:
https://github.com/Pylons/pyramid_debugtoolbar/commit/9c47df3f7b34ebbc7d8bcb9d3963520c1cc1232b

Readme & docs say 1.2a1:
https://github.com/Pylons/pyramid_debugtoolbar/blame/master/README.rst#L7
https://github.com/Pylons/pyramid_debugtoolbar/blame/master/docs/index.rst#L19

Setup says >=1.2dev:
https://github.com/Pylons/pyramid_debugtoolbar/blob/master/setup.py#L27

**Comment by inklesspen** [comment]
Since test_toolbar does not pass its requests through a Pyramid router (it generates request objects and feeds them to a tween), `request.invoke_subrequest` is not available. So test_toolbar makes a mock method. This mock method allows the tests to pass with Pyramid 1.3 even though they should not.

**Comment by mmerickel** [comment]
We've pinned the toolbar to `>= 1.4`.
