### ISSUE TITLE
logging sqlalchemy objects fails with DetachedInstanceError's

### ISSUE THREAD

**Issue by woutervb** [Pylons/pyramid_debugtoolbar#188]
When trying to log a sqlalchemy object (with a __repr__ function) using lazy logging it will fail when the debugbar is active in pyramid.

I guess this is due to the fact the pyramid has already closed the DBSession, but the debugbar then evaluates the log messages, which involves accessing the sqlalchemy objects, which no longer are part of an session.

**Comment by mmerickel** [comment]
Yeah we need to fix this by constructing the record inside of `ThreadTrackingHandler.emit` instead of later after the response is generated.
