### ISSUE TITLE
pyramid_debugtoolbar not working on aiopyramid + nginx + uWSGI + Asyncio

### ISSUE THREAD

**Issue by AnderUstarroz** [Pylons/pyramid_debugtoolbar#204]
The **pyramid_debugtoolbar** is not working on [aiopyramid](https://github.com/housleyjk/aiopyramid) + [nginx](http://nginx.com/) + [uWSGI (with Asyncio support)](http://uwsgi-docs.readthedocs.org/en/latest/asyncio.html). I don't really think it's a bug in the toolbar cause it does work with gunicorn + Asyncio. uWSGI must be blocking some request variable that is needed by the toolbar. But I'm not getting any error in my nginx, uwsgi or pyramid logs. The toolbar is simply not showing any data.  

Do you know a way to debug the toolbar and find out why is not being populated? So we can find out what's wrong on the uWSGI server

**Comment by mike-seiler** [comment]
Is it possible to display a warning to the user when this happens? the failure mode is a bit awkward and silent (and took a lot of debugging to work out)

**Comment by mcdonc** [comment]
If the server sets the 'wsgi.multiprocess' WSGI environment variable, the toolbar could bail out and refuse to do anything, I guess.  I have no idea whether this would be the right thing in general, however, or even whether the server(s) in question set the flag correctly, or how you'd indicate "well enough" that this is happening.

**Comment by mmerickel** [comment]
The toolbar will now skip requests and emit a warning if it is run in a multiprocess environment. See https://github.com/Pylons/pyramid_debugtoolbar/pull/286
