### ISSUE TITLE
configurable css_override_url

### ISSUE THREAD

**Issue by jvanasco** [Pylons/pyramid_debugtoolbar#207]
I patched this locally, but can do a PR if others find it useful (I think it is)...

I added a .ini setting of `css_override_url`.  If set, that is injected into the Exception and Toolbar templates after the core css is loaded.

The use case is allowing developers to do a few simple things with css such as making the toolbar fit more information on the screen by:

• Make the font-size smaller
• Decrease the padding on the tabs 
• Decrease the height of the toolbar nav/branding

**Comment by mmerickel** [comment]
This can be done right now by overriding the css asset doing something like:

```
# myapp/debugtoolbar.py
def includeme(config):
    config.override_asset(to_override='pyramid_debugtoolbar:static/toolbar.css', override_with='myapp:static/toolbar.css')
```

And then `debugtoolbar.includes = myapp.debugtoolbar`.
