### ISSUE TITLE
pyramid_debugtoolbar and unittests

### ISSUE THREAD

**Issue by Xuton** [Pylons/pyramid_debugtoolbar#208]
When adding python errors to warnings, "warnings.filterwarnings('error')" one cannot have  "pyramid.includes =  pyramid_debugtoolbar" in the development.ini whilst running unittests.

If you do, the exception occurs.
DeprecationWarning: The "custom_predicates" argument to Configurator.add_view is deprecated as of Pyramid 1.5.  Use "config.add_view_predicate" and use the registered view predicate as a predicate argument to add_view instead. See "Adding A Third Party View, Route, or Subscriber Predicate" in the "Hooks" chapter of the documentation for more information.

**Comment by mmerickel** [comment]
We would like to update to the new predicates api but we'd have to drop support for older versions of pyramid. The only way around this is to rewrite the view registrations to use `config.add_view` and then we can pass either `custom_predicates=` or call `add_view_predicate`.

This is totally doable, and would be the right way to go for anyone wanting to contribute a patch.

Pseudocode below:
```
view_kw = {}
if hasattr(config, 'add_view_predicate'):
    config.add_view_predicate(...)
    view_kw[...] = ...
else:
    view_kw['custom_predicates'] = (...)
config.add_view(..., **view_kw)
```

**Comment by mmerickel** [comment]
It looks like at this point pyramid_debugtoolbar requires Pyramid 1.4+ so it should be trivial to switch the implementation from custom_predicates to an actual view predicate.

**Comment by mmerickel** [comment]
The `custom_predicates` were dropped in the 2.4 release. This issue is no longer valid.
