### ISSUE TITLE
request panel should show more info

### ISSUE THREAD

**Issue by jvanasco** [Pylons/pyramid_debugtoolbar#209]
i noticed a few things about the request panel.  

i know it is labeled 'request vars', but there is a lot of 'request info' that is not there:

1. the original `request` object is not passed into the template.  everything is pre-calculated and submitted as a dict

2. because much of this is calculated off the dict, there are a lot of request attributes that could/should be there.  it's a small subset of the possible information in http://docs.pylonsproject.org/docs/pyramid/en/latest/api/request.html

it seems to miss things like:

	subpath
	traversed
	view_name
	virtual_root
	virtual_root_path
	exception
	exc_info
	matchdict
	matched_route

and dozens more. those just jumped out at me.

**Comment by mmerickel** [comment]
I'd accept a PR to expose the properties listed above.

**Comment by mmerickel** [comment]
closed via #241
