### ISSUE TITLE
Hard to use in conjunction with a Content Security Policy

### ISSUE THREAD

**Issue by dstufft** [Pylons/pyramid_debugtoolbar#211]
Browsers can leverage a [Content Security Policy](https://developer.mozilla.org/en-US/docs/Web/Security/CSP) to prevent browsers which support it from executing scripts (among other things) unless they come from a whitelisted source. This is a great way to limit the damage that an XSS attack can do if one manages to happen because, with a properly respective CSP, the browsers won't execute the script.

Retrofitting a CSP into an existing site is often difficult because existing sites often do things like rely on inline styling and inline scripts which preventing this is one of the key benefits of CSP.

What does this have to do with pyramid_debugtoolbar? When using pyramid_debugtoolbar it does both inline styles and inline scripting which means that using pyramid_debugtoolbar you need to either disable CSP or allow ``unsafe-inline`` for both of those values.

Disabling CSP is not a particularly great option, because since CSP restricts what is possible to do in a webpage if you don't run with the CSP policy enabled even when in development it's trivial to introduce changes that rely on running things inline accidentally which you're unlikely to notice until you're out of development and into staging/production when something breaks.

Allowing ``unsafe-inline`` is also not a particularly great option because preventing inline script execution is one of the key points of CSP and if you allow it unconditionally then you lose that protection but if you allow it only in development then you run into a similar issue as when you simply disable CSP.

There are two basic options to solving this.

The first is to allow the user to specify a static script nonce that the debug toolbar will use in it's script tag like ``<script type="text/javascript" nonce="the nonce">``. This would allow them to selectively allow *only* this script (although re-using a nonce isn't technically safe, so you could only do it in development). This would not protect against the use of inline styles, but needing to allow those unconditionally is not quite as bad as unconditionally allowing inline javascript.

The better solution is to simply move the js and css into seperate ``.js`` and ``.css`` files that pyramid_debugtoolbar would serve. The HTML would then be simplified since the js and css parts would be referencing files instead of being injected inline. I'm unsure if you can inject a <link> tag for the CSS at the base of the html or if it needs to be at the top, so it might require a more complicated injection process. The CSP policy would then only need to allow ``'self'`` which still might be more than people want to allow, but there's not much way around that.

**Comment by dstufft** [comment]
Just to be thorough, the current most restrictive CSP that can be set while using pyramid_debugtoolbar is:

Directive   | Most Restrictive
----------- | ----------------------
referrer    | cross-origin
connect-src | 'self'
img-src     | 'self'
script-src  | 'self' 'unsafe-inline'
style-src   | 'self' 'unsafe-inline'

**Comment by kamalgill** [comment]
+1, We're using CSP (script-src 'self') for https://github.com/eucalyptus/eucaconsole and it would be great if the inline JS could be removed.

**Comment by mmerickel** [comment]
What if you just turn off the toolbar injection via `debugtoolbar.show_on_exc_only = true`. Is this good enough for everyone? You can then open the toolbar yourself in a separate tab manually.

On exception the toolbar will take over and render the full page, which may not be what you want, but may be ok. But that's up to you to tell me.

The only answer I can come up with that satisfies *all* of the possible CSP constraints is to just turn off the toolbar injection entirely and open it manually in a separate tab.
