### ISSUE TITLE
panels: templates don't need classes on the tr

### ISSUE THREAD

**Issue by jvanasco** [Pylons/pyramid_debugtoolbar#214]
The tables in the panel templates make repeated use of this pattern:

    <tr class="${i%2 and 'pDebugEven' or 'pDebugOdd'}">

this is not necessary

1. Since the tables have the 'table-striped' class from Bootstrap, they are colored by css.
2. the pDebugEven and pDebugOdd classes are not defined in css (they were removed)

When I have time, I'll update and issue a pull request.  I just wanted to log this now, in case anyone is writing new panels.

**Comment by mmerickel** [comment]
Fixed by #221.
