### ISSUE TITLE
Unable to SELECT/EXPLAIN from query with datetime in params

### ISSUE THREAD

**Issue by inklesspen** [Pylons/pyramid_debugtoolbar#222]
The SQLAlchemy panel offers SELECT and EXPLAIN actions if two properties are met: the params are JSON-serializable and the query text starts with 'select'.

However, there are valid params which are not JSON-serializable, such as datetimes. In the Pyramid channel, @mmerickel suggested serializing the params with pickle instead.

Alternatively, a mechanism could probably be devised to let the select/explain views access the query data stored in the panels; after all, the other views have access to that data, right?

**Comment by inklesspen** [comment]
It should also probably be possible to SELECT/EXPLAIN a query with no params at all.

**Comment by mmerickel** [comment]
Yeah accessing the panels is probably ideal. So the explain would take the request id and some info about which query and then pull the actual query from the panel.
