### ISSUE TITLE
myTab jquery code keeps debugger from working

### ISSUE THREAD

**Issue by inklesspen** [Pylons/pyramid_debugtoolbar#246]
https://github.com/Pylons/pyramid_debugtoolbar/blob/414c94d376461496860b57f751c712f416cf2bf9/pyramid_debugtoolbar/templates/toolbar.dbtmako#L75-L79

The myTab dom node doesn't seem to exist; this causes a JS exception. When I comment out lines 75-79, everything works fine.

**Comment by bertjwregeer** [comment]
Want to do a PR?
