### ISSUE TITLE
Sidebar is empty when debugged application is mounted on a non-root path

### ISSUE THREAD

**Issue by lieryan** [Pylons/pyramid_debugtoolbar#266]
To reproduce:
1. Use Paste to set up composite app such that:
   1. **http://localhost:6543/myapp/** contains an application with debug toolbar enabled
   2. **http://localhost:6543/** contains a different application without debug toolbar
      
      ``` ini
      [composite:main]
      use = egg:Paste#urlmap
      / = app1
      /myapp = app2
      ```
2. Access pyramid debug toolbar in http://localhost:6543/myapp/_debug_toolbar/

Actual:
1. The debugtoolbar's sidebar (where I can select other requests) is empty.

Expected:
1. The debugtoolbar's sidebar are populated with other requests
## 

Looking at the Network tab in Firefox, I get that Debug Toolbar is trying to load the SSE endpoint in:

```
http://localhost:6543/_debug_toolbar/sse?request_id=313339373433353034363739393532
```

which returns 200 OK, but never returns useful events for /myapp.

Tested on:
- pyramid==1.6.1
- pyramid-debugtoolbar==2.1
- Paste==2.0.3
- PasteDeploy==1.5.2

**Comment by mmerickel** [comment]
I use pyramid_debugtoolbar on multiple wsgi apps via the composite component regularly without problems. I'm sure this has been fixed since 2.1.
