### ISSUE TITLE
the panel navigation assigns multiple identical "ids"

### ISSUE THREAD

**Issue by jvanasco** [Pylons/pyramid_debugtoolbar#271]
this can create issues on javascript targeting and behavior, as ids are supposed to be unique within the dom

the panels div creates this structure:

```
<li id="${panel.dom_id}">
     <a id="${panel.dom_id}">
```

https://github.com/Pylons/pyramid_debugtoolbar/blob/0933065fcc2ae943290b2ee7db0f9d9119a362d8/pyramid_debugtoolbar/templates/history_tab.dbtmako#L21-L31

The id was probably wanted on the nested `a` element for bootstrap functionality, not the `li`.

fixing this isn't hard, but will require auditing the javascript in `toolbar.js`.  It looks like the panels toggling is working via a custom solution (perhaps because of this), and not the boostrap api (which has methods to show/hide the integrated panels/tabs and hooks on entry/exit).

**Comment by mmerickel** [comment]
Just figure out which id is the important one and remove the other. I'll be happy to accept the fix. Alternatively switch to using bootstrap tabs if you really want - I don't have an opinion here.
