### ISSUE TITLE
Checkmark colors used to identify the state of the profiler is hard to discern when color blind.

### ISSUE THREAD

**Issue by monokrome** [Pylons/pyramid_debugtoolbar#273]
I don't know if this is an issue that your community is interested in tackling, but it's hard to tell if it's on or off when color blind. It may be better to have red/blue coloring instead. I'm not a graphics designer, but would be willing to try to tackle it if it makes sense for me to do so.

**Comment by bertjwregeer** [comment]
I believe right now it is using the Pyramid colour scheme, but this is a great suggestion that we will have to keep in mind.

I think right now the checkmark may actually just be a CSS styled unicode character, so it may be a fairly simple change of the CSS.

If you are comfortable diving in, by all means submit a PR, feel free to drop by #pyramid on Freenode if you have questions or pose them here!

**Comment by stevepiercy** [comment]
@monokrome you're right. The symbol should toggle between two different shapes as well.

Here's the relevant CSS:

https://github.com/Pylons/pyramid_debugtoolbar/blob/ca28c002cf5b43e5234c55739b9aa98d13df4b99/pyramid_debugtoolbar/static/toolbar/toolbar.css#L20-L30

Let's change the icon from tick-red.png to cross.png:
![cross.png](https://cloud.githubusercontent.com/assets/102112/18535113/3419de48-7aa6-11e6-9de2-c892d0074a40.png)

**Comment by stevepiercy** [comment]
I'll take this one on. It's quick and easy.

**Comment by stevepiercy** [comment]
Much better:

![google chrome008](https://cloud.githubusercontent.com/assets/102112/18535444/30a6f068-7aa9-11e6-9df4-3a6ceb89ad74.png)
![google chrome007](https://cloud.githubusercontent.com/assets/102112/18535445/30c04d56-7aa9-11e6-8fe8-fae982eaae60.png)

**Comment by stevepiercy** [comment]
Fixed in https://github.com/Pylons/pyramid_debugtoolbar/commit/ad94bd2f7d789073ed391d201f09ca80a1c164c2

This will need a release to PyPI so folks can start using it. @mmerickel ?

**Comment by monokrome** [comment]
Thanks so much, @stevepiercy & @bertjwregeer
