### ISSUE TITLE
Avoid horizontal scrolling in the SQL panel

### ISSUE THREAD

**Issue by corehack** [Pylons/pyramid_debugtoolbar#281]
Options:
1. use something like "white-space: pre-wrap;" in CSS
2. replace `<pre>` with `<div>` by subclassing pygments.formatters.HtmlFormatter
 and using `lineseparator='<br />'`

Opinions ?

**Comment by corehack** [comment]
With the CSS solution, `word-break: normal;` is useful also, to avoid breaking column names, aliases, etc

Note: #169 is related, but that issue is about complete solution, which may require long discussions and lots of code. Here, OTOH we are facing more annoying problem which could be fixed easily

**Comment by corehack** [comment]
There's also horizontal scrolling in the "SELECT" modal, but that issue is not possible to fix, I think, while using tables due to the nature of data (unlimited number of columns). Even if we truncate each row visually while adding a "..." button, with sufficiently big number of columns it will always overflow.

**Comment by mmerickel** [comment]
related: #168

**Comment by mmerickel** [comment]
Fixed via #311.
