### ISSUE TITLE
SQLAlchemy connections not being returned to pool

### ISSUE THREAD

**Issue by Deimos** [Pylons/pyramid_debugtoolbar#282]
*Note: This isn't a very important issue since I'm only using debugtoolbar in dev where I can just disable connection-pooling to avoid it anyway, but I figured I'd start an issue for it in case it could be fixed (or if this is just me doing something wrong).*

It seems like pyramid_debugtoolbar is holding SQLAlchemy connections open and not returning them to the connection pool. With the default SQLAlchemy pooling, this means that doing 15 requests fairly quickly while debugtoolbar is enabled will exhaust the pool and cause further requests to time out waiting for a connection.

Checking `ps` or selecting from `pg_stat_activity` shows the number of processes increasing with each request. If I comment out the include for pyramid_debugtoolbar (and change nothing else), that behavior stops.

Some packages/versions I'm using that could be relevant:

* psycopg2==2.7.1
* pyramid==1.8.3
* pyramid-debugtoolbar==3.0.5
* pyramid-tm==1.1.1
* SQLALchemy==1.1.9
* transaction==2.1.2
* zope.sqlalchemy==0.7.7

Thanks, let me know if any more information would be helpful, or if I just have something configured wrong and the problem is on my end.

**Comment by mmerickel** [comment]
This **should** be limited to the `debugtoolbar.max_request_history` setting (default: 100) in the worst case scenario but basically I think the SQLA panel hangs onto enough information that the connections used to perform queries stay open. This is to support the re-query/explain/analyze functionality in the toolbar and I'm not sure there's a good way around it atm since (in general) the toolbar doesn't have a way to create new database connections so it needs to hang onto the old one. It might be possible to close/reopen it if we knew exactly what was leaking.

It'd be helpful to know if you dropped the `max_request_history` down whether you saw the connections getting garbage collections properly or if they were still staying open. Hopefully they are garbage collections and then the question is what part of the panel is holding open the connection and what we can do about it.

**Comment by Deimos** [comment]
Thanks for such a quick response, I appreciate it.

It looks like reducing that setting does help some, but probably isn't a full solution. If I drop it to something quite low like 5, it still seems to behave pretty similarly. Even if I reduce it all the way to 1 I can still cause it to run out of connections, though it's definitely harder and I need to do some requests in pretty quick succession to cause it.

That seems a bit odd, is there something time-based about the way connections would be garbage collected?

**Comment by mmerickel** [comment]
> That seems a bit odd, is there something time-based about the way connections would be garbage collected?

Garbage collection runs at its own speed so that can explain part of it. You can experiment with `gc.collect()` yourself but if it's time-based it's almost certainly gc related.

**Comment by bertjwregeer** [comment]
```
alembic==0.9.1
psycopg2==2.7.1
pyramid==1.8.3
pyramid-debugtoolbar==3.0.5
pyramid-tm==1.1.1
SQLAlchemy==1.1.9
transaction==2.1.2
zope.sqlalchemy==0.7.7
```

Hitting it 15+ times in very quick succession in a with the debugtoolbar enabled doesn't do anything:

```
fulgent=# select * from pg_stat_activity;
 datid | datname |  pid  | usesysid | usename  | application_name | client_addr | client_hostname | client_port |         backend_start         |          xact_start           |          query_start          |         state_change          | wait_event_type | wait_event | state  | backend_xid | backend_xmin |              query              
-------+---------+-------+----------+----------+------------------+-------------+-----------------+-------------+-------------------------------+-------------------------------+-------------------------------+-------------------------------+-----------------+------------+--------+-------------+--------------+---------------------------------
 16386 | fulgent |  5337 |    16384 | xistence |                  | 127.0.0.1   |                 |       52784 | 2017-04-09 09:05:45.695824-06 |                               | 2017-04-14 16:16:05.467846-06 | 2017-04-14 16:16:05.467896-06 |                 |            | idle   |             |              | ROLLBACK
 16386 | fulgent | 36051 |    16384 | xistence | psql             |             |                 |          -1 | 2017-04-14 16:15:33.270988-06 | 2017-04-14 16:16:09.166925-06 | 2017-04-14 16:16:09.166925-06 | 2017-04-14 16:16:09.166929-06 |                 |            | active |             |         1012 | select * from pg_stat_activity;
(2 rows)
```

This is using the cookiestarter template for sqlalchemy from Pyramid as a started for the project.

None of the connections time out, and all of the transactions are closed at the end. The sqlalchemy debugging in the toolbar works without issues too, including `EXPLAIN` and others.

**Comment by Deimos** [comment]
Hmm, interesting. Thanks for checking that, I'll see if I can narrow down something specific that I'm doing differently that's causing it then.

**Comment by mmerickel** [comment]
@Deimos do you think there's anything more we can do here?

**Comment by Deimos** [comment]
Sorry, I haven't tried to figure out the specific cause yet. I'll close the issue though and if I come up with a better explanation someday (and it really is related to debugtoolbar), I'll open a new one or re-open. Thanks for the help and responses.

**Comment by mmerickel** [comment]
Absolutely... I'm always happy to reopen this issue if we can get some more evidence. Thanks!
