### ISSUE TITLE
change debugtoolbar.panels settings to use panel names and expect panels to be included via debugtoolbar.includes

### ISSUE THREAD

**Issue by mmerickel** [Pylons/pyramid_debugtoolbar#287]
This is a breaking change proposal to make the panels much more capable.

I'll start with a summary of some recent and related changes. For starters, I've already added `config.add_debugtoolbar_panel(...)` to master. This allows a panel (and other assets) to be included via `debugtoolbar.includes` extension points. I am interested in rewriting all panels to be included via `debugtoolbar.includes`. For example:

```python
debugtoolbar.includes =
    pyramid_debugtoolbar_dogpile
    pyramid_debugtoolbar_ajax
    pyramid_debugtoolbar.panels.introspection  # redundant as it would be included by default
```

Secondly, `debugtoolbar.active_panels` is a setting that uses the panel name instead of class path to adjust some state on the specified panels. Using the panel name is very handy here.

Proposal:

Get rid of `debugtoolbar.extra_panels` and `debugtoolbar.extra_global_panels` and change `debugtoolbar.panels` and `debugtoolbar.global_panels` to be an ordered list of panel names. By default, they are unnecessary and any panel included from `debugtoolbar.includes` would already be visible. The settings would simply be for overriding the default ordering of the panels and you would do so by referencing them by name.

I need people to weigh in on the cost-benefit to how much this may break their current workflow as well as any alternate suggestions. My goal here is to make `debugtoobar.includes` the primary way to include panels and extra configuration. I realize some panels such as pyramid_debugtoolbar_dogpile currently do things in the opposite way and use `pyramid.includes` and I think this proposed approach is more powerful.

On a side note it may be possible to maintain bw-compatibility here so it's really a question of whether this sounds like a good simplification or not.

ping @jvanasco

**Comment by jvanasco** [comment]
in the case of dogpile, I'm really just using `pyramid.includes` to ensure that a reified `config.add_request_method(` happens on the original application.  appending the panel onto `config.registry.settings['debugtoolbar.panels']` was just a convenience to make it a one-liner for enabling.

https://github.com/jvanasco/pyramid_debugtoolbar_dogpile/blob/master/pyramid_debugtoolbar_dogpile/__init__.py#L26-L36

Looking at the the debugtoolbar code... 

https://github.com/Pylons/pyramid_debugtoolbar/blob/3da6a65506fb556d7bae98f0bd57a5084900d7ef/pyramid_debugtoolbar/__init__.py#L199-L203

Is that `config` for the same application?  I know the toolbar was busted out into it's own application a year or two ago.

If it is, I can bust out a version for the new API relatively fast -- it's just shifting 3 lines.  If it's not, I'll just release a new version with a pinned max toolbar to the current release so nothing breaks until I have bandwidth to migrate to the new system.

**Comment by mmerickel** [comment]
Right, you've pointed out the one issue I've been thinking through which is how to affect the config of the main application. The `config` object in the includeme of a `debugtoolbar.includes` call is the one for the toolbar application... not the app you are instrumenting.

Currently it is possible to affect that app directly, but it may not be ideal.

```python
def includeme(config):
    parent_config = Configurator(registry=config.registry.parent_registry)
    parent_config.add_request_method(...)
    parent_config.commit()
```

I will say I do not think this is a bad approach because the purpose of the toolbar features is to try and wrap around the app without breaking it. One of the best ways to do that is actually at the end after the app is done with its own setup. I fixed a latent issue with BeforeRender ordering already by deferring registration of our own subscriber until the app is created (https://github.com/Pylons/pyramid_debugtoolbar/pull/284). I think it is actually a really good approach for anything people want to do that guarantees their code activates properly. I know this is a bit of a stream of consciousness but imagine I added another api that codified this a bit. Imagine `config.register_debugtoolbar_injector` which would take a callback and invoke it later after the parent app is done with its setup.

```python
def add_method(parent_config):
    parent_config.add_request_method(...)
config.register_debugtoolbar_injection(add_method)
```

The debugtoolbar would automatically invoke these callbacks from within an `ApplicationCreated` event and would pass it a config object to use.

**Comment by jvanasco** [comment]
This all looks good to me - it's just a couple of edits to bring things into compliance.

Personally I'm fine with breaking changes, but I do worry about the global ecosystem - especially with junior developers.  I wonder if it might be beneficial for panels (possibly other pyramid libraries too) to declare a compatibility 'string', and then debugtoolbar spits out pretty deprecation/warnings onto the console if things are out of sync.

The use-case would be something like this:

* "Bob" upgrades the toolbar and a handful of packages.
* The toolbar notes that 4 packages expose a compatible identifier, 1 does not, 3 do not expose anything.
* The toolbar prints out something like:

    Registered 3rd party toolbar panels:
        foo - compatible
        bar - compatible
        biz - incompatible, some features may not work with this toolbar
        bash - unknown
