### ISSUE TITLE
make the toolbar `request` accessible in `DebugPanel.has_content` `DebugPanel.nav_subtitle`

### ISSUE THREAD

**Issue by jvanasco** [Pylons/pyramid_debugtoolbar#298]
`__init__` is passed the "original_request" for setting up data.

`render_content` and `render_vars` are passed the "toolbar request" for displaying data

A usecase for this: now that there is an active-panel registry, one might want to reformat the data collected by another panel into a specialized view, such as reformatting the SqlAlchemy or performance panels.

In order to display `has_content` properly, one needs to access the toolbar request -- but that is not available unless one uses the recommended-against function `get_current_request`.

A potential way to address this, would be to extend the DebugPanel base class with a `toolbar_request` attribute, and then assign it to each panel in `toolbar_app.request_view`.

**Comment by mmerickel** [comment]
The current `DebugPanel` API is a holdover from before the toolbar was a separate WSGI app. If we wanted to fix it I would redesign it significantly to split the `PanelSource` from the `PanelUI` such that there were two objects each with clearly defined APIs where `PanelSource` only accessed the original request and the `PanelUI` could access the source as well as the toolbar request object. A global panel would have no source. I can tell you I have no plans to do this large amount of work at this time. If you desperately need this content in your `has_content` and `nav_subtitle` functions then I suggest you use `get_current_request` for now.
