### ISSUE TITLE
docs improvement: panels vs extra_panels

### ISSUE THREAD

**Issue by jvanasco** [Pylons/pyramid_debugtoolbar#353]
when adding a custom panel via a 3rd party package `includeme`, if no `panels` are defined (for the fallback behavior of all panels), adding the custom panel to `panels` will initialize `panels` with a single panel -- preventing the fallback behavior from happening later on: 

for example, the following will disable all the default panels:

```
def includeme(config):
    config.registry.settings['debugtoolbar.panels'].append(MyCustomPanel)
```

but adding the panel to 'extra_panels' will allow the default panels to run:

```
def includeme(config):
    config.registry.settings['debugtoolbar.extra_panels'].append(MyCustomPanel)
```

I think the docs for panels vs extra-panels, and the 'custom panels howto', should recommend panels being added to `extra_panels` when loaded by an `includeme`.

**Comment by mmerickel** [comment]
If you follow the guide and use `config.add_debugtoolbar_panel` then it is automatically injected into the default list of panels. You should not be mutating the settings.

https://docs.pylonsproject.org/projects/pyramid-debugtoolbar/en/latest/#writing-the-panel

**Comment by jvanasco** [comment]
whoa, I missed the release of that API function 2 years ago - that solves everything. thanks for adding that feature!

all my panels were written before `add_debugtoolbar_panel` existed.  the docs used to read 

> config.registry.settings['debugtoolbar.panels'].append(SampleDebugPanel)

https://github.com/Pylons/pyramid_debugtoolbar/commit/faa39cce025982103f8f1aafa32147fe87831b66#diff-caf2a6b8f4947d018f68893c695b5202
