### ISSUE TITLE
currentThread deprecation

### ISSUE THREAD

**Issue by mattpepin** [Pylons/pyramid_debugtoolbar#372]
currentThread is deprecated in favor of current_thread:

pyramid_debugtoolbar/panels/logger.py:44: DeprecationWarning: currentThread() is deprecated, use current_thread() instead
  thread = threading.currentThread()

**Comment by stevepiercy** [comment]
@mattpepin please provide more information. Please include the full stack trace, and how to reproduce the issue. Thank you!

**Comment by mattpepin** [comment]
Oh sorry, there's no stack trace per se. If you run a project with Pyramid in Python 3.10 with deprecation warnings on (python -W default), it will output this message. It's simply because currentThread() is deprecated. It was renamed to current_thread() since Python 2.6:

https://docs.python.org/3/library/threading.html#threading.current_thread
https://docs.python.org/2.7/library/threading.html#threading.currentThread

**Comment by stevepiercy** [comment]
Thank you for the explanation.

**Comment by mmerickel** [comment]
fixed in #374
