### ISSUE TITLE
problems using ajax file uploader

### ISSUE THREAD

**Issue by claudiuapetrei** [Pylons/pyramid_debugtoolbar#45]
I tried to implement the http://valums.com/ajax-upload/ script on a pyramid project.

The script send the file name as a get param and the file content in the body of the request. 

Unfortunately the toolbar crashes the request that works just fine if the toolbar is disabled.

This is what I get in the apache log: https://gist.github.com/1336696

**Comment by mmerickel** [comment]
If there is any chance you can reproduce this in later versions of the toolbar please let me know and we can investigate.
