### ISSUE TITLE
standalone exception handler

### ISSUE THREAD

**Issue by tilgovi** [Pylons/pyramid_debugtoolbar#76]
It might be nice to have an option to use pyramid_debugtoolbar's debugger like weberror's exc handler. In this case, the toolbar code would not be loaded, the JS would not be injected, but the tween (or whatever is catching the exceptions) would still be installed.

This may not be a useful configuration if #75 is implemented. It depends on how much of the JS and CSS for the toolbar can be left out when running in exception-handler-only mode.

**Comment by mmerickel** [comment]
All of this should now be possible by `debugtoolbar.show_on_exc_only = true` and the separate toolbar implementation in 2.x.
