### ISSUE TITLE
exception when remote IP makes no sense

### ISSUE THREAD

**Issue by dholth** [Pylons/pyramid_debugtoolbar#85]
``` python
  response = self.handle_request(request)
  File "pyramid_debugtoolbar/toolbar.py", line 108, in toolbar_tween
    if ipaddr.IPAddress(remote_addr) in ipaddr.IPNetwork(host):
  File "pyramid_debugtoolbar/ipaddr.py", line 85, in IPAddress
    address)
ValueError: '192.168.117.153, 216.53.134.86' does not appear to be an IPv4 or IPv6 address
```

pyramid-debugtoolbar==1.0.2

**Comment by bertjwregeer** [comment]
One of the people that saw this issue, what middleware box/server were you using?

**Comment by merwok** [comment]
Not sure what a middleware box is, but I’m pretty sure we were using nginx + uwsgi.

**Comment by bertjwregeer** [comment]
It's a fancy way of saying "proxy server", generally manufactured by big iron companies like F5/IronPort/others.

**Comment by danwerner** [comment]
Back then I was using Varnish as a caching reverse proxy. In whatever version of Varnish was current in 2013.

**Comment by mmerickel** [comment]
The REMOTE_ADDR is set in python. It’s not a header. So some wsgi component would have to be copying a header blindly into the REMOTE_ADDR key when it should be more trusted than that.
