### ISSUE TITLE
Breakdown of log message count

### ISSUE THREAD

**Issue by shish** [Pylons/pyramid_debugtoolbar#94]
Views having log messages is normal, but having messages with level="error" is not -- it'd be nice if there was some way to tell without having to open the logging tab and manually scan the list every time, eg replace "4 messages" with "4 messages (3 debug, 1 warning)", or "4 messages (3 / 1)" colouring the numbers to show the levels

**Comment by stevepiercy** [comment]
For colors, use [Twitter Bootstrap classes](http://getbootstrap.com/css/#buttons-options).

Alternatively, there are [custom classes for the status_code](https://github.com/Pylons/pyramid_debugtoolbar/blob/master/pyramid_debugtoolbar/static/toolbar/toolbar.css#L1-L9).

**Comment by adidas** [comment]
Still working on this. Unfortunately, time is something I am lacking at the moment. Anyway, I have the logic to gather the counts and display them. I just need to work on the colors now.

On a side note, I am thinking we just show anything at warning and above in the breakdown. So for example, "115 (2|0|100)" where 2 are the number of warnings, 0 is the number of errors, and 100 is the number of critical log records. It can then be inferred that the remaining 13 records are info or below.

**Comment by adidas** [comment]
I have something, but I feel like I could have done this better. That said, the end result looks like this...

![pyramid_debugtoolbar](https://user-images.githubusercontent.com/1545770/27733796-073c061e-5d66-11e7-97b9-ffbf7911439c.png)

However, to get the colors I did some pretty hacky things. That said, please take a look at 

https://github.com/Pylons/pyramid_debugtoolbar/compare/master...adidas:master

I'd appreciate any feedback.

Thanks.

**Comment by stevepiercy** [comment]
We should not return a hex color, but instead a CSS class name that aligns with 'error', 'warning', 'info', etc. Also I found a better markup using [label](http://getbootstrap.com/components/#available-variations) instead of "badge".

```html
<span class="label label-danger">Danger</span>
```

I'd say use the following styles:
* critical = label-danger
* error = label-danger
* warning = label-warning
* info = label-info
* debug = label-default
* notset = label-default

**Comment by mmerickel** [comment]
This is too much info for the allotted space. I'd consider either 

- Show the total number of messages and change the background color to indicate the highest risk level emitted. 

- Show only the highest risk color and count.

**Comment by stevepiercy** [comment]
> * Show only the highest risk color and count.

To be clear, do you mean qualitative (severity) or quantitative (count)?

I agree that 3 numbers and pipes is a little too much.

I think that the most severe message and its count and corresponding background color should be displayed. Examples:

* 0 critical, 0 error, 1 warning, 9 info, 8 debug, 0 notset → `<span class="label label-warning">1</span>`
* 1 critical, 0 error, 2 warning, 9 info, 8 debug, 0 notset → `<span class="label label-danger">1</span>`

**Comment by mmerickel** [comment]
> To be clear, do you mean qualitative (severity) or quantitative (count)?

Your examples below agree with what I was attempting to describe. The severity (log level) is what I meant by risk.

**Comment by adidas** [comment]
Sounds good.

Question: for badge class what is the best approach to changing it's color?
I tried throwing in the bootstrap class, but the badge class took precedent.

That is why I used an inline style. Another thought was to create other
badge classes to represent the various logging levels with different
background colors.

Finally, does anyone cares if I add in more colors? I don't think green is
appropriate for warnings if yellow is used for errors and red for criticals.

--Dan

**Comment by adidas** [comment]
Never mind I didn't see Steve's post.

**Comment by stevepiercy** [comment]
@adidas in case you missed it, in Bootstrap, [labels](http://getbootstrap.com/components/#available-variations) have variable background colors, but [badges](http://getbootstrap.com/components/#badges) have grey or white only and would require customization of the CSS.

**Comment by adidas** [comment]
It seems like it. I must have been trying something else. I'll try to play with the code tonight. Should be a quick change.

**Comment by stevepiercy** [comment]
Closing this issue because #322 resolved it and was merged. If not, please reopen or create a new issue.
